st_brain_outdir: /data/swamyvs/eyeintegration_splicing/testing/stringtie_build_testing/st_bt_samples/TPM_0.1_isoform_0.01_/
subtissueFile: ref/subtissues.txt
tissueFile: ref/tissues.txt
ref_GTF: /data/swamyvs/ocular_transcriptomes_pipeline/ref/gencode_comp_ano.gtf
working_dir: /data/swamyvs/pacbio_testing
lr_sample_file: sampleTableRPE_pacbio.tsv
ref_genome: /data/swamyvs/ocular_transcriptomes_pipeline/ref/gencode_genome.fa
variants: ref/encode_variants.vcf.gz
chr_names: ref/chr_fasta_entries.txt
lr_fql: /data/swamyvs/pacbio_testing/fastqs/
stringtie_version: 'stringtie/2.0.3'
scallop_version: 'scallop/0.10.4'
STAR_version: 'STAR/2.6.1c'
sr_fql: '/data/OGVFB_BG/EiaD_2019_05/'
bam_path: '/data/swamyvs/ocular_transcriptomes_pipeline/'
bedtools_version: 'bedtools/2.27.1'
sr_sampleFile: 'sampleTableRPE_V2.tsv'
minimap2_version: minimap2/2.17
samtools_version: 'samtools/1.9'
gffcompare_version: 'gffcompare/0.11.2'
salmon_version: 'salmon/1.0.0'
uniprot_file: 'ref/uniprot_human_gene_familys.tsv.gz'